Repository commonhaus/foundation, pull requests merged in 2024-05, with the labels that each got.

#147 Update trademark list
  TRADEMARKS.md
Labels: vote/open, notice

#149 Undraft the bylaws: CF Council [due: 7 May]
  bylaws/3-cf-council.md
Labels: notice, vote/done, vote/quorum

#154 Undraft the bylaws: membership [due 13 May]
  bylaws/2-cf-membership.md
Labels: vote/open, notice, vote/quorum

#158 Undraft the bylaws: decision making [due May 17]
  bylaws/5-decision-making.md
Labels: vote/open, notice, vote/quorum

#159 Undraft the bylaws: notice records [due May 23]
  bylaws/6-notice-records.md
Labels: notice, vote/done

#161 Undraft the bylaws: indemnification and dissolution [due May 27]
  bylaws/7-indemnification-dissolution.md
Labels: notice, vote/done, vote/quorum
